Xcode 14 compatibility
RedMadRobot/apexy-ios pull request #39
Opened 2022-07-15 11:55 UTC by annakocheshkova96

Xcode 14 doesn't allow to mark lazy properties as `@available`. See https://stackoverflow.com/a/55534141/7453375

2022-07-15 18:40 UTC, subdan requested changes
Thanks for the PR. Please fix typo and remove unnecessary code `= nil`.

2022-07-15 18:40 UTC, subdan commented on Sources/ApexyLoader/ContentLoader.swift
> +    // Can not use `@available` with lazy properties on XCode 14. This is a workaround.
```suggestion
    // Can not use `@available` with lazy properties in Xcode 14. This is a workaround.
```
🙈

2022-07-15 18:40 UTC, subdan commented on Sources/ApexyLoader/ContentLoader.swift
> +    private var storedStatePublisher: Any? = nil
```suggestion
    private var storedStatePublisher: Any?
```

2022-07-15 18:40 UTC, subdan commented on Sources/ApexyLoader/ContentLoader.swift
> +    private var storedStateSubject: Any? = nil
```suggestion
    private var storedStateSubject: Any?
```

2022-07-16 14:10 UTC, subdan approved these changes

2022-07-18 10:02 UTC, annakocheshkova96 commented
@subdan can we release this change after the merge?

2022-07-18 10:14 UTC, subdan commented
Yes

2022-07-23 14:54 UTC, laqiguy approved these changes

2022-07-23 14:55 UTC, merged